"""Automated code review and fix.

Pipeline: shallow clone → gather commits/diffs → detect project type → run the
project's own linter and tests → scan the diff for secrets and common defects →
report. Fixes are generated by Claude Code in headless mode inside the clone,
re-verified, and only ever pushed to a new branch after explicit approval.

Nothing here merges, force-pushes, or touches the default branch.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import shutil
import secrets as secrets_mod
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from ghbot.git.runner import platform_env
from ghbot.logging_setup import get_redactor
from ghbot.validators import RepoRef, ValidationError

if TYPE_CHECKING:
    from ghbot.services.container import Services

SEVERITIES = ("critical", "high", "medium", "low")
DEFAULT_DEPTH = 20
MAX_DEPTH = 200
COMMAND_TIMEOUT = 300  # seconds for one linter/test/audit command

# Patterns that must never reach Telegram or the Claude Code prompt.
SECRET_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("GitHub token", re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}")),
    ("GitHub fine-grained token", re.compile(r"\bgithub_pat_[A-Za-z0-9_]{20,}")),
    ("AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("Slack token", re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}")),
    ("Google API key", re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b")),
    ("private key", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |PGP )?PRIVATE KEY-----")),
    ("Telegram bot token", re.compile(r"\b\d{6,12}:[A-Za-z0-9_-]{30,}")),
    ("generic secret assignment", re.compile(
        r"(?i)\b(?:api[_-]?key|secret|password|passwd|token)\s*[:=]\s*[\"'][A-Za-z0-9/+_-]{16,}[\"']")),
)

RISKY_PATTERNS: tuple[tuple[str, str, str, re.Pattern[str]], ...] = (
    ("high", "unhandled promise", "Promise without .catch() or await: a rejection would be unhandled.",
     re.compile(r"^\+.*\b(?:fetch|axios|\w+\.then)\s*\([^)]*\)\s*(?!.*\.catch)(?!.*await).*$")),
    ("medium", "possible null dereference",
     "Value from a lookup that can return null/undefined is used directly.",
     re.compile(r"^\+.*\b(?:querySelector|getElementById|\.find\(|\.get\()[^;]*\)\s*\.\w+")),
    ("high", "bare except", "Bare 'except:' swallows every error, including KeyboardInterrupt.",
     re.compile(r"^\+\s*except\s*:\s*$")),
    ("medium", "shell injection risk", "subprocess call with the shell enabled.",
     re.compile(r"^\+.*shell\s*=\s*True")),
    ("high", "eval on input", "eval()/exec() on a runtime value.",
     re.compile(r"^\+.*\b(?:eval|exec)\s*\(")),
)

_LOG_ERROR_RE = re.compile(
    r"(?i)(\berror\b|err!|\bfailed\b|\bfailure\b|\bexception\b|\bfatal\b|not found|cannot|"
    r"no such file|traceback|\bE\d{3}\b|✗|×)")

ENV_FILE_RE = re.compile(r"^\+\+\+ b/(.*(?:^|/)\.env(?:\.[\w-]+)?)$", re.M)


def redact(text: str) -> str:
    """Remove secrets before anything leaves the machine (Telegram or the model prompt)."""
    result = get_redactor()(text)
    for _, pattern in SECRET_PATTERNS:
        result = pattern.sub("[REDACTED_SECRET]", result)
    return result


@dataclass
class Finding:
    severity: str
    title: str
    detail: str
    file: str | None = None
    line: int | None = None
    source: str = "scan"
    fixable: bool = True

    @property
    def location(self) -> str:
        if not self.file:
            return "-"
        return f"{self.file}:{self.line}" if self.line else self.file


@dataclass
class ReviewResult:
    repo: str
    project_type: str
    commits: list[str] = field(default_factory=list)
    files: list[str] = field(default_factory=list)
    findings: list[Finding] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    clone: Path | None = None
    head_sha: str = ""
    read_only: bool = False
    ci_logs: str = ""  # error lines from failed GitHub jobs, used when generating a fix

    @property
    def fixable(self) -> list[Finding]:
        return [f for f in self.findings if f.fixable]

    def by_severity(self) -> dict[str, list[Finding]]:
        return {level: [f for f in self.findings if f.severity == level] for level in SEVERITIES}


@dataclass
class FixResult:
    branch: str
    changed_files: list[str]
    diff_stat: str
    diff_head: str
    verified: bool
    verification: str
    claude_summary: str


class ReviewError(Exception):
    """Something in the pipeline failed. The message is already redacted."""


async def run_command(args: list[str], cwd: Path, timeout: int, env_extra: dict[str, str] | None = None
                      ) -> tuple[int, str]:
    """Run one command without a shell, capped by a timeout, output redacted."""
    env = {
        **platform_env(),
        "PATH": os.environ.get("PATH", "/usr/local/bin:/usr/bin:/bin"),
        "HOME": os.environ.get("HOME", str(cwd)),
        "LANG": "C.UTF-8",
        "CI": "1",
        "NO_COLOR": "1",
        **(env_extra or {}),
    }
    for passthrough in ("ANTHROPIC_API_KEY", "CLAUDE_CODE_OAUTH_TOKEN", "NVM_BIN", "NODE_PATH"):
        if passthrough in os.environ:
            env[passthrough] = os.environ[passthrough]
    try:
        process = await asyncio.create_subprocess_exec(
            *args, cwd=str(cwd), env=env,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
        )
    except FileNotFoundError:
        return 127, f"{args[0]}: not found"
    try:
        stdout, _ = await asyncio.wait_for(process.communicate(), timeout=timeout)
    except TimeoutError:
        process.kill()
        await process.wait()
        return 124, f"{args[0]}: timed out after {timeout}s"
    return process.returncode or 0, redact(stdout.decode("utf-8", "replace"))


class ReviewService:
    def __init__(self, services: Services) -> None:
        self.s = services
        self._busy: dict[int, str] = {}  # chat id -> what is running

    # ------------------------------------------------------------- run state
    def busy_with(self, chat_id: int) -> str | None:
        return self._busy.get(chat_id)

    def start_run(self, chat_id: int, label: str) -> None:
        if chat_id in self._busy:
            raise ReviewError(f"A review is already running ({self._busy[chat_id]}). Wait for it to finish.")
        self._busy[chat_id] = label

    def finish_run(self, chat_id: int) -> None:
        self._busy.pop(chat_id, None)

    # --------------------------------------------------------------- helpers
    def claude_available(self) -> bool:
        return shutil.which(self.s.settings.claude_code_path) is not None

    async def check_access(self, repo: RepoRef, force: bool) -> tuple[bool, dict[str, Any]]:
        """Returns (owned, metadata). Repos you do not own need --force and stay read-only."""
        owned = repo.owner.lower() == self.s.username.lower()
        if not owned and not force:
            raise ValidationError(
                f"{repo.full_name} is not owned by {self.s.username}. Pass --force to review it read-only "
                "(no linters, no tests, no fixes)."
            )
        meta = await self.s.gh.get_repo(repo.full_name) if owned else {}
        if owned:
            self.s.policy.check_writable_meta(meta)
        return owned, meta

    # ----------------------------------------------------------------- clone
    async def clone(self, repo: RepoRef, depth: int) -> Path:
        root = self.s.settings.review_dir
        root.mkdir(parents=True, exist_ok=True)
        target = root / f"{repo.name}-{secrets_mod.token_hex(4)}"
        url = self.s.backups.url_for(repo.full_name)
        await asyncio.to_thread(
            lambda: self.s.git.run(["clone", "--depth", str(depth), "--no-tags", "--", url, str(target)], auth=True)
        )
        return target

    async def gather(self, clone: Path, depth: int) -> tuple[list[str], str, list[str], str]:
        def git(args: list[str]) -> str:
            return self.s.git.run(args, cwd=clone).stdout

        log = await asyncio.to_thread(git, ["log", f"-{depth}", "--format=%h %an: %s"])
        commits = [line for line in log.splitlines() if line.strip()]
        head = (await asyncio.to_thread(git, ["rev-parse", "--short", "HEAD"])).strip()
        range_spec = f"HEAD~{min(depth, max(len(commits) - 1, 1))}..HEAD" if len(commits) > 1 else "HEAD"
        diff_args = ["diff", "--unified=3", range_spec] if len(commits) > 1 else ["show", "--unified=3", "HEAD"]
        diff = redact(await asyncio.to_thread(git, diff_args))
        names = await asyncio.to_thread(
            git, ["diff", "--name-only", range_spec] if len(commits) > 1 else ["show", "--name-only", "--format=", "HEAD"]
        )
        files = sorted({line.strip() for line in names.splitlines() if line.strip()})
        return commits, diff, files, head

    # --------------------------------------------------------------- analysis
    def detect_project(self, clone: Path) -> str:
        if (clone / "package.json").is_file():
            return "node"
        if any((clone / name).is_file() for name in ("requirements.txt", "pyproject.toml", "setup.py")):
            return "python"
        if (clone / "go.mod").is_file():
            return "go"
        if (clone / "Cargo.toml").is_file():
            return "rust"
        return "unknown"

    def scan_diff(self, diff: str, files: list[str]) -> list[Finding]:
        findings: list[Finding] = []
        current_file = None
        line_no = 0
        for raw in diff.splitlines():
            if raw.startswith("+++ b/"):
                current_file = raw[6:]
                line_no = 0
                continue
            if raw.startswith("@@"):
                match = re.search(r"\+(\d+)", raw)
                line_no = int(match.group(1)) - 1 if match else 0
                continue
            if raw.startswith("+") and not raw.startswith("+++"):
                line_no += 1
                for name, pattern in SECRET_PATTERNS:
                    if pattern.search(raw):
                        findings.append(Finding("critical", f"possible {name} committed",
                                                "A value matching a secret pattern was added. Rotate it and remove "
                                                "it from history.", current_file, line_no, "secret-scan", False))
                        break
                for severity, title, detail, pattern in RISKY_PATTERNS:
                    if pattern.search(raw):
                        findings.append(Finding(severity, title, detail, current_file, line_no, "diff-scan"))
            elif not raw.startswith("-"):
                line_no += 1
        for path in files:
            name = path.rsplit("/", 1)[-1]
            if name == ".env" or name.startswith(".env."):
                findings.append(Finding("critical", "environment file committed",
                                        f"{path} is tracked in git; secrets in it are exposed.", path, None,
                                        "file-scan", False))
        return findings

    async def run_linters(self, clone: Path, project: str) -> tuple[list[Finding], str]:
        findings: list[Finding] = []
        output_parts: list[str] = []
        for args, label in self._lint_commands(clone, project):
            code, output = await run_command(args, clone, COMMAND_TIMEOUT)
            output_parts.append(f"$ {' '.join(args)}\n{output.strip()[:4000]}")
            if code == 127:
                continue
            if code != 0:
                findings.extend(self._parse_tool_output(output, label))
        return findings, "\n\n".join(output_parts)

    def _lint_commands(self, clone: Path, project: str) -> list[tuple[list[str], str]]:
        commands: list[tuple[list[str], str]] = []
        if project == "node":
            package = self._package_json(clone)
            scripts = package.get("scripts", {})
            if "lint" in scripts:
                commands.append((["npm", "run", "--silent", "lint"], "eslint"))
            if "typecheck" in scripts:
                commands.append((["npm", "run", "--silent", "typecheck"], "tsc"))
            elif (clone / "tsconfig.json").is_file():
                commands.append((["npx", "--no-install", "tsc", "--noEmit"], "tsc"))
        elif project == "python":
            if (clone / "pyproject.toml").is_file() or (clone / "ruff.toml").is_file():
                commands.append((["ruff", "check", "--output-format", "concise", "."], "ruff"))
        elif project == "go":
            commands.append((["go", "vet", "./..."], "go vet"))
        return commands

    async def run_tests(self, clone: Path, project: str) -> tuple[list[Finding], str]:
        args: list[str] | None = None
        if project == "node" and "test" in self._package_json(clone).get("scripts", {}):
            args = ["npm", "test", "--silent"]
        elif project == "python" and any((clone / n).exists() for n in ("tests", "test")):
            args = ["python", "-m", "pytest", "-q", "--no-header", "-x"]
        elif project == "go":
            args = ["go", "test", "./..."]
        if args is None:
            return [], ""
        code, output = await run_command(args, clone, COMMAND_TIMEOUT)
        if code in (0, 127):
            return [], output[:4000]
        failures = [line for line in output.splitlines()
                    if re.search(r"(?i)\b(fail(ed|ure)?|assert|error)\b", line)][:10]
        finding = Finding("high", "tests failing", "; ".join(f.strip()[:120] for f in failures) or "test run failed",
                          None, None, "tests")
        return [finding], output[:4000]

    async def github_checks(self, repo: RepoRef, shas: list[str]) -> tuple[list[Finding], list[str]]:
        """What GitHub itself reports for these commits: failed check runs, annotations, failed jobs.

        This is what the red ✗ next to a commit on github.com means; it is independent of
        whatever linter or test script exists locally.
        """
        findings: list[Finding] = []
        notes: list[str] = []
        seen_checks: set[int] = set()
        for sha in shas:
            runs = await self.s.gh.check_runs(repo.full_name, sha)
            if runs.get("forbidden"):
                notes.append("Check results are not readable with this token (needs Checks: read).")
                break
            for check in runs.get("check_runs", []):
                if check.get("status") != "completed" or check.get("conclusion") in (
                        "success", "neutral", "skipped", None):
                    continue
                if check["id"] in seen_checks:
                    continue
                seen_checks.add(check["id"])
                name = check.get("name", "check")
                conclusion = check.get("conclusion")
                annotations = await self.s.gh.check_run_annotations(repo.full_name, check["id"])
                if annotations:
                    for note in annotations[:10]:
                        findings.append(Finding(
                            "high" if note.get("annotation_level") == "failure" else "medium",
                            f"{name}: {redact(note.get('title') or note.get('message', ''))[:80]}",
                            redact(note.get("message", ""))[:300],
                            note.get("path"), note.get("start_line"), "github-checks",
                        ))
                else:
                    detail = redact((check.get("output") or {}).get("summary") or "")[:300]
                    findings.append(Finding("high", f"check failed: {name}",
                                            detail or f"GitHub reports '{conclusion}' for commit {sha[:7]}.",
                                            None, None, "github-checks"))
            statuses = await self.s.gh.combined_status(repo.full_name, sha)
            for item in statuses.get("statuses", []):
                if item.get("state") in ("failure", "error"):
                    findings.append(Finding("high", f"status failed: {item.get('context', 'status')}",
                                            redact(item.get("description") or "")[:200] or "commit status failed",
                                            None, None, "github-checks"))
        if findings:
            notes.append(f"{len(findings)} problem(s) come from GitHub's own checks on these commits.")
        return findings, notes

    async def failed_job_details(self, repo: RepoRef, sha: str, max_lines: int = 15) -> str:
        """Error lines from the failed jobs of a commit's workflow runs, for the fix prompt."""
        chunks: list[str] = []
        for run in await self.s.gh.runs_for_sha(repo.full_name, sha):
            if run.get("conclusion") not in ("failure", "timed_out", "cancelled"):
                continue
            for job in await self.s.gh.run_jobs(repo.full_name, run["id"]):
                if job.get("conclusion") != "failure":
                    continue
                failed_steps = [s.get("name") for s in job.get("steps", []) if s.get("conclusion") == "failure"]
                logs = await self.s.gh.job_logs(repo.full_name, job["id"])
                lines = logs.splitlines()
                errors = [line for line in lines if _LOG_ERROR_RE.search(line)][-max_lines:]
                if not errors:  # nothing matched: show the tail so the failure is never empty
                    errors = lines[-max_lines:]
                chunks.append(redact("\n".join([
                    f"Workflow: {run.get('name')} · job: {job.get('name')}",
                    f"Failed steps: {', '.join(s for s in failed_steps if s) or 'unknown'}",
                    *errors,
                ]))[:2000])
        return "\n\n".join(chunks)

    async def npm_audit(self, clone: Path, project: str) -> tuple[list[Finding], str]:
        if project != "node" or not (clone / "package-lock.json").is_file():
            return [], ""
        code, output = await run_command(["npm", "audit", "--json", "--audit-level=high"], clone, COMMAND_TIMEOUT)
        if code == 127:
            return [], ""
        try:
            data = json.loads(output[output.index("{"):])
        except (ValueError, json.JSONDecodeError):
            return [], output[:2000]
        findings = []
        for name, entry in (data.get("vulnerabilities") or {}).items():
            severity = entry.get("severity", "low")
            if severity in ("high", "critical"):
                findings.append(Finding(severity, f"vulnerable dependency {name}",
                                        f"npm audit reports a {severity} advisory for {name}.",
                                        "package.json", None, "npm audit"))
        return findings, output[:2000]

    def _package_json(self, clone: Path) -> dict[str, Any]:
        try:
            return json.loads((clone / "package.json").read_text())
        except (OSError, ValueError):
            return {}

    # ------------------------------------------------------------- pipelines
    async def review_commits(self, repo: RepoRef, depth: int, *, force: bool = False, progress=None) -> ReviewResult:
        owned, _ = await self.check_access(repo, force)
        depth = max(1, min(int(depth), MAX_DEPTH))
        if progress:
            await progress(f"📥 Cloning {repo.name} (depth {depth})…")
        clone = await self.clone(repo, depth)
        result = ReviewResult(repo.full_name, "unknown", clone=clone, read_only=not owned)
        if progress:
            await progress("🔍 Reading commits and diffs…")
        result.commits, diff, result.files, result.head_sha = await self.gather(clone, depth)
        result.project_type = self.detect_project(clone)
        result.findings.extend(self.scan_diff(diff, result.files))
        if not owned:
            result.notes.append("Read-only review: linters, tests and fixes are skipped for repositories "
                                "you do not own.")
            return result
        if progress:
            await progress("⚙️ Reading GitHub check results…")
        check_findings, check_notes = await self.github_checks(
            repo, [line.split()[0] for line in result.commits[:5] if line.strip()] or [result.head_sha]
        )
        result.findings.extend(check_findings)
        result.notes.extend(check_notes)
        if check_findings:
            if progress:
                await progress("📄 Reading the failed job logs…")
            first_sha = (result.commits[0].split()[0] if result.commits else result.head_sha)
            result.ci_logs = await self.failed_job_details(repo, first_sha)

        lint_commands = self._lint_commands(clone, result.project_type)
        if progress:
            await progress(f"🧪 Running {result.project_type} linters…" if lint_commands
                           else "🧪 No linter configured, skipping…")
        lint_findings, _ = await self.run_linters(clone, result.project_type)
        result.findings.extend(lint_findings)
        if not lint_commands:
            result.notes.append("No linter or typechecker is configured in this repository.")
        if progress:
            await progress("🧪 Running tests…")
        test_findings, test_output = await self.run_tests(clone, result.project_type)
        result.findings.extend(test_findings)
        if not test_output:
            result.notes.append("No test suite is configured in this repository.")
        audit_findings, _ = await self.npm_audit(clone, result.project_type)
        result.findings.extend(audit_findings)
        order = {level: index for index, level in enumerate(SEVERITIES)}
        result.findings.sort(key=lambda f: order.get(f.severity, 9))
        return result

    async def review_issue(self, repo: RepoRef, number: int, *, force: bool = False, progress=None) -> ReviewResult:
        owned, _ = await self.check_access(repo, force)
        issue = await self.s.gh.client.get(f"/repos/{repo.full_name}/issues/{int(number)}")
        if issue.get("pull_request"):
            raise ValidationError(f"#{number} is a pull request, not an issue.")
        if progress:
            await progress(f"📥 Cloning {repo.name} for issue #{number}…")
        clone = await self.clone(repo, DEFAULT_DEPTH)
        result = ReviewResult(repo.full_name, self.detect_project(clone), clone=clone, read_only=not owned)
        result.head_sha = (await asyncio.to_thread(
            lambda: self.s.git.run(["rev-parse", "--short", "HEAD"], cwd=clone).stdout)).strip()
        title = redact(issue.get("title") or "")
        body = redact(issue.get("body") or "")[:4000]
        result.notes.append(f"Issue #{number}: {title}")
        result.findings.append(Finding("high", f"issue #{number}: {title[:80]}",
                                       body.strip()[:400] or "No description.", None, None, "issue"))
        candidates = self._files_for_issue(clone, f"{title}\n{body}")
        result.files = candidates
        if candidates:
            result.notes.append("Likely files: " + ", ".join(candidates[:10]))
        else:
            result.notes.append("No obviously related files found; Claude Code will search the repository.")
        return result

    def _files_for_issue(self, clone: Path, text: str) -> list[str]:
        words = {w.lower() for w in re.findall(r"[A-Za-z_][A-Za-z0-9_.-]{3,}", text)}
        matches: list[str] = []
        for path in clone.rglob("*"):
            if not path.is_file() or ".git/" in str(path):
                continue
            relative = str(path.relative_to(clone))
            stem = path.stem.lower()
            if stem in words or relative.lower() in words:
                matches.append(relative)
            if len(matches) >= 20:
                break
        return sorted(matches)

    # ------------------------------------------------------------------ fix
    def build_task(self, result: ReviewResult) -> str:
        lines = [
            f"Repository: {result.repo} ({result.project_type} project).",
            "Fix the following problems found by an automated review.",
            "Make the smallest correct change for each. Do not reformat unrelated code,",
            "do not add dependencies, and do not change public APIs.",
            "",
        ]
        for finding in result.fixable:
            lines.append(f"- [{finding.severity}] {finding.location}: {finding.title} — {finding.detail}")
        if result.ci_logs:
            lines += ["", "Failing CI output:", "```", result.ci_logs[:3000], "```"]
        lines += ["", "After editing, make sure the project's linter and tests still pass."]
        return redact("\n".join(lines))

    async def generate_fix(self, result: ReviewResult, progress=None) -> FixResult:
        if result.clone is None or result.read_only:
            raise ReviewError("No writable clone for this review.")
        if not self.claude_available():
            raise ReviewError(
                f"Claude Code CLI not found at '{self.s.settings.claude_code_path}'. Install it with "
                "'curl -fsSL https://claude.ai/install.sh | bash' and set CLAUDE_CODE_PATH."
            )
        clone = result.clone
        branch = f"bot/fix-{result.head_sha or 'head'}-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}"
        await asyncio.to_thread(lambda: self.s.git.run(["checkout", "-b", branch], cwd=clone))

        if progress:
            await progress("🤖 Claude Code is preparing a fix…")
        timeout = self.s.settings.review_timeout_ms // 1000
        code, output = await run_command(
            [self.s.settings.claude_code_path, "-p", self.build_task(result),
             "--output-format", "json", "--permission-mode", "acceptEdits"],
            clone, timeout,
        )
        if code == 124:
            await self._reset(clone)
            raise ReviewError(f"Claude Code timed out after {timeout}s; nothing was changed.")
        if code != 0:
            await self._reset(clone)
            raise ReviewError(f"Claude Code failed (exit {code}): {output.strip()[-400:]}")
        summary = self._claude_summary(output)

        changed = await self._changed_files(clone)
        limit = self.s.settings.max_files_per_fix
        if not changed:
            await self._reset(clone)
            raise ReviewError("Claude Code made no changes.")
        if len(changed) > limit:
            await self._reset(clone)
            raise ReviewError(f"The fix touched {len(changed)} files, above the limit of {limit} "
                              "(MAX_FILES_PER_FIX). Nothing was kept.")

        if progress:
            await progress(f"🔁 Re-running linters and tests on {len(changed)} changed file(s)…")
        lint_findings, lint_output = await self.run_linters(clone, result.project_type)
        test_findings, test_output = await self.run_tests(clone, result.project_type)
        verified = not lint_findings and not test_findings
        verification = redact("\n".join(filter(None, [lint_output[-1500:], test_output[-1500:]])) or "no checks configured")

        def git(args: list[str]) -> str:
            return self.s.git.run(args, cwd=clone).stdout

        # Stage first: new files are untracked, so a plain `git diff` would show nothing.
        await asyncio.to_thread(git, ["add", "-A"])
        diff_stat = redact(await asyncio.to_thread(git, ["diff", "--cached", "--stat"]))
        diff_head = redact("\n".join((await asyncio.to_thread(git, ["diff", "--cached"])).splitlines()[:40]))
        return FixResult(branch, changed, diff_stat, diff_head, verified, verification, summary)

    def _claude_summary(self, output: str) -> str:
        try:
            data = json.loads(output)
        except (ValueError, json.JSONDecodeError):
            return redact(output.strip()[-500:])
        if isinstance(data, dict):
            return redact(str(data.get("result") or data.get("summary") or "")[:800])
        return redact(str(data)[:800])

    async def _changed_files(self, clone: Path) -> list[str]:
        out = await asyncio.to_thread(lambda: self.s.git.run(["status", "--porcelain"], cwd=clone).stdout)
        return sorted({line[3:].strip() for line in out.splitlines() if line.strip()})

    async def _reset(self, clone: Path) -> None:
        def reset() -> None:
            self.s.git.run(["reset", "--hard"], cwd=clone, check=False)
            self.s.git.run(["clean", "-fd"], cwd=clone, check=False)

        await asyncio.to_thread(reset)

    async def commit_push_and_pr(self, repo: RepoRef, result: ReviewResult, fix: FixResult,
                                 progress=None) -> dict[str, Any]:
        """Approved path: commit on the fix branch, push it, open a DRAFT pull request."""
        if result.clone is None:
            raise ReviewError("The temporary clone is gone; run /review again.")
        clone = result.clone
        name, email = self._identity()
        message = f"fix: address {len(result.fixable)} finding(s) from automated review"

        def commit() -> None:
            self.s.git.run(["add", "-A"], cwd=clone)  # idempotent: generate_fix already staged
            self.s.git.run(["-c", f"user.name={name}", "-c", f"user.email={email}",
                            "commit", "-m", message], cwd=clone)

        await asyncio.to_thread(commit)
        if progress:
            await progress(f"🚀 Pushing {fix.branch}…")
        url = self.s.backups.url_for(repo.full_name)
        await asyncio.to_thread(
            lambda: self.s.git.run(["push", url, f"HEAD:refs/heads/{fix.branch}"], cwd=clone, auth=True)
        )
        body = self._pr_body(result, fix)
        meta = await self.s.gh.get_repo(repo.full_name)
        pull = await self.s.gh.create_pull(repo.full_name, title=message, head=fix.branch,
                                           base=meta.get("default_branch", "main"), body=body, draft=True)
        record = await self.s.db.create_pull_request(
            account=self.s.active, repo=repo.full_name, number=pull["number"], branch=fix.branch,
            base=meta.get("default_branch", "main"), change_type="review-fix", title=message, status="open",
            auto_merge=0, merge_method="squash", delete_branch=0, head_sha=pull["head"]["sha"],
            html_url=pull["html_url"], operation_id=None,
        )
        await self.s.db.log_simple("review_fix_pr", repo.full_name, "done",
                                   params={"branch": fix.branch, "files": len(fix.changed_files)},
                                   result={"number": pull["number"], "url": pull["html_url"]})
        return {"number": pull["number"], "url": pull["html_url"], "record_id": record.id, "draft": True}

    def _identity(self) -> tuple[str, str]:
        account = self.s.account
        return (account.display_name or account.username,
                account.email or f"{account.username}@users.noreply.github.com")

    def _pr_body(self, result: ReviewResult, fix: FixResult) -> str:
        lines = ["## Automated review fix", "",
                 f"Findings addressed ({len(result.fixable)}):", ""]
        lines += [f"- **{f.severity}** `{f.location}` — {f.title}: {f.detail}" for f in result.fixable]
        lines += ["", "### Changed files", ""]
        lines += [f"- `{path}`" for path in fix.changed_files]
        lines += ["", "### Verification", "",
                  "Linter and tests were re-run after the changes: "
                  + ("passed." if fix.verified else "see below."), "",
                  "```", fix.verification[-1000:], "```", "",
                  "Opened as a draft by the GitHub Telegram bot. Review before merging."]
        return redact("\n".join(lines))

    async def cleanup(self, result: ReviewResult | None) -> None:
        if result and result.clone:
            await asyncio.to_thread(shutil.rmtree, result.clone, True)
            result.clone = None
